name: Build & Publish image to Docker Hub

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths: 
      - 'api/Dockerfile'
      - 'front-end-nextjs/Dockerfile'

jobs:
  publish_images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Install gcloud CLI
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Build & Push Docker images
        run: |
          gcloud auth configure-docker me-west1-docker.pkg.dev
          docker build -t me-west1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/qr-code-generator-repo/api:latest ./api
          docker build -t me-west1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/qr-code-generator-repo/front-end-nextjs:latest ./front-end-nextjs
          docker push me-west1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/qr-code-generator-repo/api:latest
          docker push me-west1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/qr-code-generator-repo/front-end-nextjs:latest